<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>manipulators</name>
    <version>1.0.0</version>
    <description>High-level control for easy use of manipulators.</description>
    <author email="italo.almirante@unimore.it">italo</author>
    <maintainer email="354861@studenti.unimore.it">matteo</maintainer>
    <license>Apache License</license>

    <buildtool_depend>ament_cmake</buildtool_depend>
    <buildtool_depend>ament_cmake_python</buildtool_depend>
    <depend>rclcpp</depend>

    <depend>std_msgs</depend>
    <depend>std_srvs</depend>
    <depend>geometry_msgs</depend>
    <depend>sensor_msgs</depend>
    <depend>graph_msgs</depend>
    <depend>trajectory_msgs</depend>
    <depend>manipulator_interfaces</depend>
    <depend>detection_interfaces</depend>
    <depend>moveit_msgs</depend>
    <depend>tf2_geometry_msgs</depend>

    <depend>moveit_common</depend>
    <depend>moveit_core</depend>
    <depend>moveit_ros_planning</depend>
    <depend>moveit_ros_planning_interface</depend>

    <depend>tf2_ros</depend>
    <depend>motors_trajectory</depend>
    <depend>rviz_visual_tools</depend>
    <depend>Eigen3</depend>
    <depend>yaml_cpp_vendor</depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
