## Configuration file used by the drivers configuration

velocity_topic:     /arm_controller/command # gripper command: /gripper_controller/command

joints_names_group: [torso_lift_joint, arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint arm_7_joint]

kp:                 1.0

spinner_rate:       500

min_motor_speed:    0.001