## Configuration file used by the drivers configuration

velocity_topic:     /ur_rtde/controllers/joint_velocity_controller/command

joints_names_group: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]

kp:                 1.0

spinner_rate:       500

min_motor_speed:    0.001
real_joint_state_topic: /fake/joint_state

joint_state_timeout:  2.0
