#Refer to joy documentation to get the values for the buttons
#Thresholds and max values refer to the absolute value of the axes multiplied by 'scale', so for example if the threshold is 0.5, the axis must be at least 0.5 or -0.5 to be considered active.
mapping:
  real_time:
    enable:
      type: button
      id: 7 #L3
    joint_1_unlock: 
      type: axis
      id: 4 #L2
      threshold_up: 0.5
    joint_2_unlock: 
      type: axis
      id: 4 #L2
      threshold: 0.5
    joint_3_unlock:
      type: axis
      id: 5 #R2
      threshold: 0.5
    joint_4_unlock:
      type: axis
      id: 5 #R2
      threshold: 0.5
    joint_5_unlock:
      type: button
      id: 9 #L1
    joint_6_unlock:
      type: button
      id: 9 #L1
    joint_1_move:
      type: axis
      id: 1 #Left stick vertical
      threshold: 0.1
      max: 1.0
      scale: -1.0
    joint_2_move:
      type: axis
      id: 3 #Right stick vertical
      threshold: 0.1
      max: 1.0
      scale: -1.0
    joint_3_move:
      type: axis
      id: 0 #Left stick horizontal
      threshold: 0.1
      max: 1.0
      scale: -1.0
    joint_4_move:
      type: axis
      id: 3 #Right stick vertical
      threshold: 0.1
      max: 1.0
      scale: -1.0  
    joint_5_move:
      type: axis
      id: 0 #Left stick horizontal
      threshold: 0.1
      max: 1.0
      scale: -1.0
    joint_6_move:
      type: axis
      id: 1 #Left stick vertical
      threshold: 0.1
      max: 1.0
      scale: -1.0
  jacobian:
    enable:
      type: button
      id: 8 #R3
    unlock_tcp_rot:
      type: button
      id: 10 #R1
    tcp_move_x:
      type: axis
      id: 0 #Left stick horizontal
      threshold: 0.1
      max: 1.0
      scale: 1.0
    tcp_move_y:
      type: axis
      id: 1 #Left stick vertical
      threshold: 0.1
      max: 1.0
      scale: 1.0
    tcp_move_z:
      type: axis
      id: 3 #Right stick vertical
      threshold: 0.1
      max: 1.0
      scale: 1.0
    tcp_rot_x:
      type: axis
      id: 0 #Right stick vertical
      threshold: 0.1
      max: 1.0
      scale: 1.0
    tcp_rot_y:
      type: axis
      id: 1 #L2 button (left trigger)
      threshold: 0.5
      scale: 1.0
    tcp_rot_z:
      type: axis
      id: 3 #R2 button (right trigger)
      threshold: 0.5
      scale: 1.0
  gripper:
    open:
      type: button
      id: 11 #Dpad up
    close:
      type: button
      id: 12 #Dpad down
  known_poses:
    list: ["home_gripper_down", "home_gripper_front"]
    home_gripper_down:
      type: button
      id: 0 #Cross
    home_gripper_front:
      type: button
      id: 2 #Sqare