group_name: "manipulator"               # Manipulator group name

lin_step  : 0.01                        # Vel step factor to map joy axes into translations

rot_step  : 0.08                        # Vel step factor to map joy axes into rotations

controller: "Android"                   # Controller name, default "PS4" or "Logitech"

joint_home: [0.,-90.,-90.,-90.,+90.,0.] # Home pose, default: [0.,-90.,-90.,0.,+90.,0.]

base_name : base_link                   # Reference frame name

joint_name: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]