home_gripper_down: [0., -90., -90., -90., 90., 0.]

home_gripper_front: [0., -90., -90., -0., 90., 0.]

home_maintenance: [30, -90., -90., -28., 90., -17]

temp: [31.0, -94.0, -104.0, -40.0, 90.0, -17.0]
