## Configuration file used by the planner

manipulator_name: manipulator

name: manipulator

joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]

ee_name: tcp_gripper

base_name: base_link

vel_factor: 0.5   # Starting from a lower factor is suggested, in simulation 0.5 works fine

acc_factor: 0.5   # Starting from a lower factor is suggested, in simulation 0.5 works fine

ros_freq: 10      # ROS loop frequency

inst_kine:  false # True if the motors instantaneously reach the goal after an invKine computation, false otherwise