## Configuration file used by the planner

manipulator_name: manipulator

joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]

ee_name: tool0

base_name: base_link