## Configuration file used by the planner

manipulator_name: manipulator

joint_names:      [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]

ee_name:          tcp_gripper

base_name:        base_link

vel_factor:       0.2

acc_factor:       0.2

ros_freq:         500           # ROS loop frequency (update rate of callbacks)

inst_kine:        true          # True if the motors instantaneously reach the goal after an invKine computation

sample_time:      0.002         # Time distance between two consecutive points of the cartesian trajectory computed

max_speed_ee:     0.5       # Maximum velocity     of the end-effector in [m/s]  in cartesian planning/jacobian real time control

max_accel_ee:     0.5       # Maximum acceleration of the end-effector in [m/s2] in cartesian planning/jacobian real time control

max_spd_jnts:     3.14      # Maximum velocity     of the joints in [rad/s]  in real time speed control

max_acc_jnts:     2.0       # Maximum acceleration of the joints in [rad/s2] in real time speed control

# name:           ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
